name: Release Builds

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0

env:
  NODE_VERSION: '18'

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      - name: Install server dependencies
        run: |
          cd server
          npm ci

      - name: Install electron dependencies
        run: |
          cd electron
          npm ci

      - name: Build frontend
        run: npm run build

      - name: Build server
        run: npm run server:build

      - name: Sync Capacitor
        run: npm run cap:sync

      - name: Build Electron TypeScript
        run: |
          cd electron
          npm run build

      - name: Build Electron app
        run: |
          cd electron
          npm run build:mac
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
          CSC_LINK: ""
          CSC_KEY_PASSWORD: ""

      - name: Create artifacts directory
        run: mkdir -p artifacts

      - name: Copy built files
        run: |
          find electron/dist -name "*.dmg" -exec cp {} artifacts/ \;
          find electron/dist -name "*.zip" -exec cp {} artifacts/ \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CCC-macOS
          path: artifacts/*

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}